/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      'imgs.search.brave.com',
      'd24f1whwu8r3u4.cloudfront.net',
      '3.bp.blogspot.com',
      'cdn.kastatic.org',
      'simpleprogrammer.com',
      'images.unsplash.com',
      'cdn-media-1.freecodecamp.org',
      '4.bp.blogspot.com',
      'www.udacity.com',
      's3.amazonaws.com',
      'jaredthenerd.com',
      'cdn-media-2.freecodecamp.org',
      'techcrunch.com',
      'avatars.githubusercontent.com',
      'twimgs.com',
      '2e8ram2s1li74atce18qz5y1-wpengine.netdna-ssl.com',
      'i0.wp.com',
      'www.udacity.com',
      'cdn.sanity.io',
      'imageio.forbes.com',
      'www.grokcode.com',
      'www.careertoolbelt.com',
      'd.novoresume.com',
      'www.careercup.com',
      'pilbox.themuse.com',
      'coda.newjobs.com',
      'dorigan.com',
      'blog.codinghorror.com',
      '2e8ram2s1li74atce18qz5y1-wpengine.netdna-ssl.com',
      'www.udacity.com',
      'martincmartin.wordpress.com',
    ],
  },
};

module.exports = nextConfig;
